services:
  meet-antlr:
    container_name: meet-antlr
    image: meet-antlr
    restart: unless-stopped
    stdin_open: true
    tty: true
    build:
      dockerfile: docker/Dockerfile
      context: ../
    working_dir: /opt/app
    volumes:
      - ../:/opt/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY
    command: bash -c "tail -f /dev/null"
